<?php
/**
 * Block Information & Attributes File.
 *
 * @since 2.0.0
 *
 * @package uagb
 */


return array(
	'classMigrate'                 => false,
	'separatorAlign'                 => 'center',
	'separatorAlignTablet'             => 'center',
	'separatorAlignMobile'                 => 'center',
	'separatorStyle'               => 'solid',
	'separatorThickness'              => 4,
	'thicknessUnit'              	=> 'px',
	'separatorWidth'               => 30,
	'separatorWidthTablet'         => 30,
	'separatorWidthMobile'         => 30,
	'separatorWidthType'           => '%',
	'separatorColor' => '',
	// padding.
	'separatorTopPadding'              => '',
	'separatorRightPadding'            => '',
	'separatorLeftPadding'             => '',
	'separatorBottomPadding'           => '',
	'separatorPaddingTopTablet'        => '',
	'separatorPaddingRightTablet'      => '',
	'separatorPaddingLeftTablet'       => '',
	'separatorPaddingBottomTablet'     => '',
	'separatorPaddingTopMobile'        => '',
	'separatorPaddingRightMobile'      => '',
	'separatorPaddingLeftMobile'       => '',
	'separatorPaddingBottomMobile'     => '',
	'separatorPaddingUnit'             => 'px',
	'separatorMobilePaddingUnit'       => 'px',
	'separatorTabletPaddingUnit'       => 'px',
	'separatorPaddingLink'             => '',
	'elementType' => 'none',
	'elementPosition'	=> 'center',
	'elementPositionTablet'	=> 'center',
	'elementPositionMobile'	=> 'center',
	'elementSpacing'	=> 15,
	'elementSpacingTablet'	=> 15,
	'elementSpacingMobile'	=> 15,
	'elementSpacingUnit'	=> 'px',
	'elementTextFontFamily'	=> 'Default',
	'elementTextFontWeight'	=> '',
	'elementTextFontSize'	=> '',
	'elementTextFontSizeType'	=> 'px',
	'elementTextFontSizeTablet'	=> '',
	'elementTextFontSizeMobile'	=> '',
	'elementTextLineHeightType'	=> 'em',
	'elementTextLineHeight'	=> '',
	'elementTextLineHeightTablet'	=> '',
	'elementTextLineHeightMobile'	=> '',
	'elementTextFontStyle'	=> 'normal',
	'elementTextLetterSpacing'	=> '',
	'elementTextLetterSpacingTablet'	=> '',
	'elementTextLetterSpacingMobile'	=> '',
	'elementTextLetterSpacingType'	=> 'px',
	'elementTextDecoration'	=> '',
	'elementTextTransform'	=> '',
	'elementColor'	=> '',
	'elementIconWidth'	=> '',
	'elementIconWidthTablet'	=> '',
	'elementIconWidthMobile'	=> '',
	'elementIconWidthType'	=> 'px',
);
